version: '3'

services:
  db:
    container_name: starter
    image: "postgres:9.6.1"
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - "./pgdata:/var/lib/postgresql/data"

volumes:
  pgdata: